# Generated by Django 4.2.1 on 2023-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newvision', '0002_news_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
