# Generated by Django 4.2.1 on 2023-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newvision', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('link_url', models.URLField()),
            ],
        ),
    ]
