# Generated by Django 4.2.1 on 2023-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newvision', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
